---
resources:
- name: release
  type: git
  source:
    uri: git@github.com:bosh-packages/cf-cli-release
    private_key: {{release-repo-github-key}}
    branch: main

- name: v6-cli
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli
    private_key: {{release-repo-github-key}}
    branch: v6

- name: v7-cli
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli
    private_key: {{release-repo-github-key}}
    branch: v7

- name: v8-cli
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli
    private_key: {{release-repo-github-key}}
    branch: v8

- name: concourse-cve-scan
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/concourse-cve-scan.git
    branch: main

jobs:
- name: check-for-cves-release
  plan:
  - in_parallel:
      - get: concourse-cve-scan
      - get: release
        trigger: true
  - task: scan-with-syft-and-grype
    input_mapping:
      bosh-release-repo: release
    file: concourse-cve-scan/tasks/scan-for-cves/scan-for-cves.yml
    params:
      GRYPE_FAILURE_LEVEL: critical

- name: check-for-cves-cli-v6
  plan:
  - in_parallel:
      - get: concourse-cve-scan
      - get: v6-cli
        trigger: true
  - task: scan-with-syft-and-grype
    input_mapping:
      bosh-release-repo: v6-cli
    file: concourse-cve-scan/tasks/scan-for-cves/scan-for-cves.yml
    params:
      GRYPE_FAILURE_LEVEL: critical

- name: check-for-cves-cli-v7
  plan:
  - in_parallel:
      - get: concourse-cve-scan
      - get: v7-cli
        trigger: true
  - task: scan-with-syft-and-grype
    input_mapping:
      bosh-release-repo: v7-cli
    file: concourse-cve-scan/tasks/scan-for-cves/scan-for-cves.yml
    params:
      GRYPE_FAILURE_LEVEL: critical

- name: check-for-cves-cli-v8
  plan:
  - in_parallel:
      - get: concourse-cve-scan
      - get: v8-cli
        trigger: true
  - task: scan-with-syft-and-grype
    input_mapping:
      bosh-release-repo: v8-cli
    file: concourse-cve-scan/tasks/scan-for-cves/scan-for-cves.yml
    params:
      GRYPE_FAILURE_LEVEL: critical