name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
    - "v9.*"
    - "v8.*"
    - "v7.*"

jobs:
  acquire_binaries:
    runs-on: ubuntu-latest
    steps:
        - name: Setup upterm session
          if: always()
          uses: lhotari/action-upterm@v1
          timeout-minutes: 60
